import Foundation
import Darwin

public final class UnixSocketServer: @unchecked Sendable {
  public let path: String; private var fd: Int32 = -1
  public init(path: String) { self.path = path }
  public func start() throws { fd = socket(AF_UNIX, SOCK_STREAM, 0); guard fd >= 0 else { throw POSIXError(.EIO) }; unlink(path); var address = sockaddr_un(); address.sun_family = sa_family_t(AF_UNIX); path.withCString { ptr in withUnsafeMutableBytes(of: &address.sun_path) { raw in raw.copyBytes(from: UnsafeRawBufferPointer(start: ptr, count: min(path.utf8.count, raw.count - 1))) } }; let len = socklen_t(MemoryLayout<sockaddr_un>.size); let result = withUnsafePointer(to: &address) { $0.withMemoryRebound(to: sockaddr.self, capacity: 1) { Darwin.bind(fd, $0, len) } }; guard result == 0, listen(fd, 4) == 0 else { throw POSIXError(.EADDRINUSE) }; chmod(path, 0o600) }
  public func accept(timeout: TimeInterval = 10, ioTimeout: TimeInterval = 10) throws -> FileHandle { var pollfd = Darwin.pollfd(fd: fd, events: Int16(POLLIN), revents: 0); guard Darwin.poll(&pollfd, 1, Int32(timeout * 1000)) > 0 else { throw POSIXError(.ETIMEDOUT) }; let client = Darwin.accept(fd, nil, nil); guard client >= 0 else { throw POSIXError(.EIO) }; let wholeSeconds = Int(ioTimeout); var timeValue = timeval(tv_sec: wholeSeconds, tv_usec: Int32((ioTimeout - Double(wholeSeconds)) * 1_000_000)); setsockopt(client, SOL_SOCKET, SO_RCVTIMEO, &timeValue, socklen_t(MemoryLayout<timeval>.size)); setsockopt(client, SOL_SOCKET, SO_SNDTIMEO, &timeValue, socklen_t(MemoryLayout<timeval>.size)); return FileHandle(fileDescriptor: client, closeOnDealloc: true) }
  deinit { if fd >= 0 { close(fd); unlink(path) } }
}

public enum UnixSocketClient { public static func send(_ data: Data, path: String, timeout: TimeInterval = 10) throws -> Data { let fd = socket(AF_UNIX, SOCK_STREAM, 0); guard fd >= 0 else { throw POSIXError(.EIO) }; defer { close(fd) }; let wholeSeconds = Int(timeout); var timeValue = timeval(tv_sec: wholeSeconds, tv_usec: Int32((timeout - Double(wholeSeconds)) * 1_000_000)); setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &timeValue, socklen_t(MemoryLayout<timeval>.size)); setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &timeValue, socklen_t(MemoryLayout<timeval>.size)); var address = sockaddr_un(); address.sun_family = sa_family_t(AF_UNIX); path.withCString { ptr in withUnsafeMutableBytes(of: &address.sun_path) { raw in raw.copyBytes(from: UnsafeRawBufferPointer(start: ptr, count: min(path.utf8.count, raw.count - 1))) } }; let connected = withUnsafePointer(to: &address) { $0.withMemoryRebound(to: sockaddr.self, capacity: 1) { Darwin.connect(fd, $0, socklen_t(MemoryLayout<sockaddr_un>.size)) } }; guard connected == 0 else { throw POSIXError(POSIXErrorCode(rawValue: errno) ?? .ECONNREFUSED) }; let handle = FileHandle(fileDescriptor: fd, closeOnDealloc: false); try ChromiumFramer.writeFrame(data, to: handle); return try ChromiumFramer.readFrame(from: handle, timeout: timeout) }
}
